name: carousell-post-test

on:
  schedule:
    - cron: '0 * * * *'
  push:
  workflow_dispatch:

jobs:
  carousell-post-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Browserless Chrome
        run: |
          docker network create browserless-net
          docker run -d --network browserless-net --hostname browserless --name test -p 3000:3000 -e "DEFAULT_LAUNCH_ARGS=[\"--window-size=1920,3080\"]" browserless/chrome:1.57-chrome-stable
      - name: Sleep for 120 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'
      - name: docker ps -a
        run: |
          docker ps -a
          docker logs test
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit_sha || github.sha }}
      - name: test local browserless response
        run: |
          curl -vLk http://localhost:3000
          node -v
          npm -v
          node
      - name: monitor search result
        run: |
          ./test.sh

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: |
            carousell-search-scrape/screens/*.png
            carousell-post-scrape/screens/*.png

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./public
